import { Injectable } from '@angular/core';
import { Palabra } from './../models/palabra';
@Injectable({
  providedIn: 'root'
})
export class PalabraService {

  listaPalabras:Array<any>;
  constructor() {
    this.listaPalabras = new Array<Palabra>();
    this.listaPalabras = [
      {
        id:1,
        palabraIngles:"wolf",
        palabraEspanol:"lobo",
        urlImagen:"assets/img/lobo.png",
      },
      {
        id:2,
        palabraIngles:"cat",
        palabraEspanol:"gato",
        urlImagen:"assets/img/gato.png",
      },
      {
        id:3,
        palabraIngles:"dog",
        palabraEspanol:"perro",
        urlImagen:"assets/img/perro.png",
      },
      {
        id:4,
        palabraIngles:"shark",
        palabraEspanol:"tiburon",
        urlImagen:"assets/img/tiburon.png",
      },
      {
        id:5,
        palabraIngles:"lion",
        palabraEspanol:"leon",
        urlImagen:"assets/img/leon.png",
      },
      {
        id:6,
        palabraIngles:"sheep",
        palabraEspanol:"oveja ",
        urlImagen:"assets/img/oveja.png",
      },
      {
        id:7,
        palabraIngles:"rabbit",
        palabraEspanol:"conejo",
        urlImagen:"assets/img/conejo.png",
      },
      {
        id:8,
        palabraIngles:"duck",
        palabraEspanol:"pato",
        urlImagen:"assets/img/pato.png",
      },
      {
        id:9,
        palabraIngles:"elefant",
        palabraEspanol:"elefante",
        urlImagen:"assets/img/elefante.png",
      },
      {
        id:10,
        palabraIngles:"pig",
        palabraEspanol:"chancho",
        urlImagen:"assets/img/chancho.png",
      },
      {
        id:11,
        palabraIngles:"blackboard",
        palabraEspanol:"pizarron",
        urlImagen:"assets/img/pizarron.png",
      },
      {
        id:12,
        palabraIngles:"backpack",
        palabraEspanol:"mochila",
        urlImagen:"assets/img/mochila.png",
      },
      {
        id:13,
        palabraIngles:"book",
        palabraEspanol:"libro",
        urlImagen:"assets/img/libro.png",
      },
      {
        id:14,
        palabraIngles:"pencil",
        palabraEspanol:"lápiz",
        urlImagen:"assets/img/lapiz.png",
      },
      {
        id:15,
        palabraIngles:"crayon",
        palabraEspanol:"crayon",
        urlImagen:"assets/img/crayon.png",
      },
      {
        id:16,
        palabraIngles:"ruler",
        palabraEspanol:"regla",
        urlImagen:"assets/img/regla.png",
      },
      {
        id:17,
        palabraIngles:"scissor",
        palabraEspanol:"tijera",
        urlImagen:"assets/img/tijera.png",
      },
      {
        id:18,
        palabraIngles:"eraser",
        palabraEspanol:"borrador",
        urlImagen:"assets/img/borrador.png",
      },
      {
        id:19,
        palabraIngles:"glue",
        palabraEspanol:"plasticola",
        urlImagen:"assets/img/plasticola.png",
      },
      {
        id:20,
        palabraIngles:"marker",
        palabraEspanol:"marcador",
        urlImagen:"assets/img/marcador.png",
      },
      {
        id:21,
        palabraIngles:"jean",
        palabraEspanol:"vaquero",
        urlImagen:"assets/img/vaquero.png",
      },
      {
        id:22,
        palabraIngles:"sock",
        palabraEspanol:"media",
        urlImagen:"assets/img/media.png",
      },
      {
        id:23,
        palabraIngles:"vest",
        palabraEspanol:"chaleco",
        urlImagen:"assets/img/chaleco.png",
      },
      {
        id:24,
        palabraIngles:"pyjama",
        palabraEspanol:"pijama",
        urlImagen:"assets/img/pijama.png",
      },
      {
        id:25,
        palabraIngles:"shoe",
        palabraEspanol:"zapatilla",
        urlImagen:"assets/img/zapatilla.png",
      },
      {
        id:26,
        palabraIngles:"boot",
        palabraEspanol:"bota",
        urlImagen:"assets/img/botas.png",
      },
      {
        id:27,
        palabraIngles:"dress",
        palabraEspanol:"vestido",
        urlImagen:"assets/img/vestido.png",
      },
      {
        id:28,
        palabraIngles:"glasses",
        palabraEspanol:"lentes",
        urlImagen:"assets/img/lentes.png",
      },
      {
        id:29,
        palabraIngles:"heels",
        palabraEspanol:"tacones",
        urlImagen:"assets/img/tacones.png",
      },
      {
        id:30,
        palabraIngles:"skirt",
        palabraEspanol:"falda",
        urlImagen:"assets/img/falda.png",
      },
    ]
   }
   getPalabras(){
     return this.listaPalabras;
   }

   getPalabra(i:number){
     return this.listaPalabras[i];
   }
}
